/** Natural SEO keyword pools — avoid stuffing; use page-relevant subsets only. */

export const BRAND_KEYWORDS = [
  "Quizzical",
  "quizzical",
  "Quizziqal",
  "Quizzical SA",
  "Quizzical South Africa",
  "Quizzical Quiz Game",
  "Quizzical App",
  "Quizzical Online",
  "quizzical.site",
  "quizzical games",
  "play quizzical",
];

export const CORE_QUIZ_KEYWORDS = [
  "quiz games",
  "online quiz games",
  "trivia games",
  "trivia quiz",
  "quiz website",
  "knowledge quiz",
  "educational quiz",
  "AI quiz platform",
  "general knowledge quiz",
  "free quiz games",
  "play quizzes online",
  "online trivia platform",
  "quiz competition",
  "quiz challenges",
];

export const SOUTH_AFRICA_KEYWORDS = [
  "quiz games South Africa",
  "trivia South Africa",
  "South African quiz",
  "online quiz South Africa",
  "educational games South Africa",
  "quiz platform South Africa",
  "best quiz website South Africa",
  "South African trivia",
];

/** Legacy export — prefer CORE + page-specific pools in metadata. */
export const BASE_KEYWORDS = [
  ...BRAND_KEYWORDS,
  ...CORE_QUIZ_KEYWORDS,
  "free online quiz",
  "picture quiz",
  "flag quiz",
  "learn while playing",
];

export const PAGE_KEYWORDS = {
  home: [
    ...BRAND_KEYWORDS,
    ...CORE_QUIZ_KEYWORDS,
    ...SOUTH_AFRICA_KEYWORDS,
    "Knowledge Explorer",
    "AI-powered quiz",
  ],
  ai: [
    ...BRAND_KEYWORDS,
    "AI quiz generator",
    "custom trivia maker",
    "generate quiz online",
  ],
  signin: [...BRAND_KEYWORDS, "quizzical sign in", "quiz account"],
  signup: [...BRAND_KEYWORDS, "quizzical sign up", "free quiz account"],
  about: [
    ...BRAND_KEYWORDS,
    ...SOUTH_AFRICA_KEYWORDS.slice(0, 4),
    "about quizzical",
    "educational quiz platform",
  ],
  founder: [
    ...BRAND_KEYWORDS,
    ...SOUTH_AFRICA_KEYWORDS.slice(0, 3),
    "Zama Shange",
    "South African developer",
    "BDL Corp",
  ],
  privacy: [...BRAND_KEYWORDS, "privacy policy"],
  contact: [...BRAND_KEYWORDS, "contact quizzical"],
  status: [...BRAND_KEYWORDS, "platform status"],
};

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  geography: [
    "geography quiz",
    "country quiz",
    "capital cities quiz",
    "flags quiz",
    "world geography game",
    "guess the country",
    "landmarks quiz",
  ],
  history: [
    "history quiz",
    "historical figures quiz",
    "world history trivia",
    "presidents quiz",
  ],
  "science-and-nature": [
    "science quiz",
    "space quiz",
    "biology quiz",
    "chemistry quiz",
    "animal quiz",
    "wildlife quiz",
  ],
  sports: [
    "football quiz",
    "soccer quiz",
    "sports trivia",
    "guess the footballer",
    "sports knowledge quiz",
    "cricket quiz",
    "basketball quiz",
  ],
  entertainment: [
    "celebrity quiz",
    "movie quiz",
    "TV show quiz",
    "guess the celebrity",
    "music quiz",
    "film trivia",
  ],
  "art-and-literature": [
    "literature quiz",
    "book quiz",
    "author quiz",
    "art quiz",
  ],
  languages: ["language quiz", "vocabulary quiz", "word quiz"],
  trivia: [
    "general knowledge quiz",
    "food quiz",
    "food trivia",
    "world cuisine quiz",
    "pub quiz online",
  ],
};

export const IMAGE_GAME_KEYWORDS: Record<string, string[]> = {
  celebrity: ["guess the celebrity", "celebrity picture quiz", "famous people quiz"],
  athlete: ["guess the athlete", "sports picture quiz"],
  football: ["guess the footballer", "soccer player quiz"],
  basketball: ["guess the basketball player", "NBA player quiz"],
  cricket: ["guess the cricketer", "cricket player quiz"],
  movie: ["guess the movie", "movie poster quiz", "film picture quiz"],
  music: ["guess the singer", "music artist quiz", "band picture quiz"],
};

export const QUIZ_LONGTAIL_KEYWORDS = [
  "play free online",
  "timed quiz",
  "educational reveal",
  "multiple choice quiz",
  "mobile friendly quiz",
];

/** Search-query style topics Google indexes — each becomes /topics/{slug}. */
export const SEARCH_TOPIC_KEYWORDS = [
  "box office quiz",
  "music quiz online",
  "football quiz online",
  "soccer quiz online",
  "premier league quiz",
  "pub quiz online",
  "movie quiz online",
  "celebrity quiz online",
  "geography quiz online",
  "history quiz online",
  "science quiz online",
  "sports quiz online",
  "trivia quiz online",
  "picture quiz online",
  "flag quiz online",
  "free quiz online",
  "online quiz free",
  "quiz games online",
  "trivia games online",
  "general knowledge quiz online",
  "world capitals quiz",
  "country flags quiz",
  "guess the country quiz",
  "NBA quiz",
  "cricket quiz online",
  "basketball quiz online",
  "tennis quiz",
  "rugby quiz",
  "Olympics quiz",
  "World Cup quiz",
  "Champions League quiz",
  "La Liga quiz",
  "anime quiz",
  "Disney quiz",
  "Marvel quiz",
  "Harry Potter quiz",
  "Star Wars quiz",
  "TV show quiz online",
  "Netflix quiz",
  "pop music quiz",
  "rock music quiz",
  "hip hop quiz",
  "K-pop quiz",
  "90s music quiz",
  "80s music quiz",
  "capital cities quiz online",
  "world geography quiz",
  "African countries quiz",
  "South Africa quiz",
  "European countries quiz",
  "US states quiz",
  "animal quiz online",
  "space quiz online",
  "science trivia online",
  "math quiz online",
  "brain teaser quiz",
  "IQ quiz",
  "personality quiz",
  "true or false quiz",
  "picture round quiz",
  "emoji quiz",
  "logo quiz",
  "brand quiz",
  "food quiz online",
  "wine quiz",
  "beer quiz",
  "Christmas quiz",
  "Halloween quiz",
  "Easter quiz",
  "kids quiz online",
  "family quiz night",
  "classroom quiz",
  "teacher quiz",
  "study quiz",
  "revision quiz",
  "exam prep quiz",
  "university quiz",
  "college trivia",
  "bar quiz",
  "virtual pub quiz",
  "Zoom quiz",
  "multiplayer quiz",
  "live quiz",
  "daily quiz",
  "quiz of the day",
  "quick quiz",
  "5 minute quiz",
  "hard quiz",
  "easy quiz",
  "beginner quiz",
  "expert quiz",
  "quiz for adults",
  "quiz for teens",
  "quiz for kids",
  "picture trivia",
  "visual quiz",
  "image quiz online",
  "photo quiz",
  "guess the picture",
  "guess the flag",
  "guess the landmark",
  "landmarks quiz",
  "famous people quiz",
  "historical figures quiz",
  "presidents quiz",
  "kings and queens quiz",
  "ancient history quiz",
  "World War quiz",
  "mythology quiz",
  "Bible quiz",
  "religion quiz",
  "philosophy quiz",
  "literature quiz online",
  "book quiz online",
  "Shakespeare quiz",
  "poetry quiz",
  "art quiz online",
  "painting quiz",
  "architecture quiz",
  "invention quiz",
  "technology quiz",
  "computer quiz",
  "coding quiz",
  "AI quiz",
  "science and nature quiz",
  "biology quiz online",
  "chemistry quiz online",
  "physics quiz",
  "astronomy quiz",
  "planet quiz",
  "dinosaur quiz",
  "ocean quiz",
  "weather quiz",
  "environment quiz",
  "sustainability quiz",
  "health quiz",
  "medicine quiz",
  "anatomy quiz",
  "language quiz online",
  "Spanish quiz",
  "French quiz",
  "German quiz",
  "vocabulary quiz online",
  "spelling quiz",
  "grammar quiz",
  "word quiz online",
  "crossword quiz",
  "riddle quiz",
  "logic quiz",
  "puzzle quiz",
  "mind quiz",
  "knowledge quiz online",
  "learning quiz",
  "educational quiz online",
  "fun quiz online",
  "random quiz",
  "mixed trivia",
  "quiz night online",
  "trivia night",
  "quiz competition online",
  "leaderboard quiz",
  "score quiz",
  "timed trivia",
  "speed quiz",
  "challenge quiz",
];
