import type { AchievementDef } from "./types";

export const ACHIEVEMENTS: AchievementDef[] = [
  {
    id: "world-traveler",
    title: "World Traveler",
    description: "Learn 100 countries, cities, or landmarks",
    emoji: "🌍",
    target: 100,
    metric: "discoveries_geography",
  },
  {
    id: "sports-fanatic",
    title: "Sports Fanatic",
    description: "Answer 500 sports questions correctly",
    emoji: "⚽",
    target: 500,
    metric: "correct_sports",
  },
  {
    id: "movie-buff",
    title: "Movie Buff",
    description: "Complete 100 entertainment quizzes",
    emoji: "🎬",
    target: 100,
    metric: "quizzes_entertainment",
  },
  {
    id: "history-lover",
    title: "History Lover",
    description: "Learn 200 historical facts",
    emoji: "📜",
    target: 200,
    metric: "discoveries_history",
  },
  {
    id: "science-explorer",
    title: "Science Explorer",
    description: "Master science quizzes (80% mastery)",
    emoji: "🔬",
    target: 80,
    metric: "mastery_science-and-nature",
  },
  {
    id: "dedicated",
    title: "Dedicated",
    description: "Maintain a 30-day streak",
    emoji: "🔥",
    target: 30,
    metric: "longest_streak",
  },
  {
    id: "knowledge-collector",
    title: "Knowledge Collector",
    description: "Discover 1,000 items",
    emoji: "📚",
    target: 1000,
    metric: "discovery_count",
  },
  {
    id: "perfect-player",
    title: "Perfectionist",
    description: "Score perfect on 25 quizzes",
    emoji: "💯",
    target: 25,
    metric: "perfect_quizzes",
  },
  {
    id: "quiz-marathon",
    title: "Quiz Marathon",
    description: "Complete 200 quizzes",
    emoji: "🏃",
    target: 200,
    metric: "quizzes_completed",
  },
  {
    id: "level-50",
    title: "Halfway to Legend",
    description: "Reach level 50",
    emoji: "⭐",
    target: 50,
    metric: "level",
  },
];

export const BADGES: { id: string; label: string; emoji: string; unlock: string }[] = [
  { id: "explorer", label: "Knowledge Explorer", emoji: "🧭", unlock: "level_5" },
  { id: "world-traveler", label: "World Traveler", emoji: "🌍", unlock: "achievement_world-traveler" },
  { id: "sports-expert", label: "Sports Expert", emoji: "⚽", unlock: "mastery_sports_50" },
  { id: "movie-buff", label: "Movie Buff", emoji: "🎬", unlock: "achievement_movie-buff" },
  { id: "music-master", label: "Music Master", emoji: "🎵", unlock: "mastery_entertainment_50" },
  { id: "genius", label: "Genius", emoji: "🧠", unlock: "level_35" },
  { id: "streak-master", label: "Streak Master", emoji: "🔥", unlock: "streak_30" },
  { id: "champion", label: "Champion", emoji: "🏆", unlock: "level_50" },
];
