/** Shared SEO keyword pools for Quizzical.site */

export const BASE_KEYWORDS = [
  "quizzical",
  "quizzical.site",
  "free online quiz",
  "free quiz games",
  "online trivia",
  "trivia game",
  "quiz game online",
  "play quiz free",
  "educational quiz",
  "interactive quiz",
  "learn while playing",
  "multiple choice quiz",
  "timed quiz game",
  "solo quiz game",
  "quiz for adults",
  "quiz for students",
  "fun trivia online",
  "brain game",
  "knowledge quiz",
];

export const PAGE_KEYWORDS = {
  home: [
    "best free quiz site",
    "online quiz platform",
    "picture quiz games",
    "flag quiz",
    "celebrity quiz",
    "movie trivia",
    "sports quiz",
    "geography trivia",
    "AI quiz",
    "random quiz generator",
  ],
  ai: [
    "AI quiz generator",
    "AI trivia maker",
    "create quiz with AI",
    "custom quiz generator",
    "generate quiz online free",
    "AI quiz maker",
    "topic quiz generator",
    "ChatGPT quiz",
    "automatic quiz creator",
    "make your own quiz",
  ],
};

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  geography: [
    "geography quiz",
    "world geography trivia",
    "capital cities quiz",
    "flags of the world",
    "country quiz",
    "map quiz",
    "guess the country",
    "landmarks quiz",
    "world capitals game",
    "flag guessing game",
  ],
  history: [
    "history quiz",
    "world history trivia",
    "WWII quiz",
    "historical trivia",
    "presidents quiz",
    "ancient history quiz",
  ],
  "science-and-nature": [
    "science quiz",
    "nature quiz",
    "space quiz",
    "solar system quiz",
    "biology quiz",
    "animal quiz",
    "science trivia online",
  ],
  sports: [
    "sports quiz",
    "sports trivia",
    "football quiz",
    "guess the footballer",
    "athlete quiz",
    "Olympics quiz",
    "sports legends trivia",
  ],
  entertainment: [
    "movie quiz",
    "film trivia",
    "entertainment quiz",
    "guess the movie",
    "Hollywood quiz",
    "pop culture quiz",
  ],
  "art-and-literature": [
    "literature quiz",
    "book quiz",
    "author quiz",
    "art quiz",
    "classic novels quiz",
    "famous painters quiz",
  ],
  languages: [
    "language quiz",
    "words quiz",
    "alphabet quiz",
    "vocabulary trivia",
    "world languages quiz",
  ],
  trivia: [
    "general knowledge quiz",
    "random trivia",
    "fun facts quiz",
    "pub quiz online",
    "general trivia questions",
  ],
};

export const IMAGE_GAME_KEYWORDS: Record<string, string[]> = {
  celebrity: [
    "guess the celebrity",
    "celebrity picture quiz",
    "who is this celebrity",
    "famous people quiz",
    "celebrity photo game",
    "star quiz",
  ],
  athlete: [
    "guess the athlete",
    "sports picture quiz",
    "footballer photo quiz",
    "NBA player quiz",
    "athlete photo game",
  ],
  movie: [
    "guess the movie",
    "movie poster quiz",
    "film picture quiz",
    "movie scene quiz",
    "cinema trivia game",
  ],
  music: [
    "guess the singer",
    "music artist quiz",
    "band picture quiz",
    "pop star quiz",
    "music trivia game",
  ],
};
