import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Award,
  BookOpen,
  Brain,
  Building2,
  Calendar,
  CircleCheck,
  CircleHelp,
  ClipboardList,
  Clapperboard,
  Cookie,
  Flame,
  FlaskConical,
  Gamepad2,
  Globe,
  Handshake,
  Languages,
  Landmark,
  Lightbulb,
  Link2,
  Mail,
  Medal,
  MessageSquare,
  Palette,
  Pin,
  Radio,
  Rocket,
  Settings,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  Telescope,
  Trophy,
  Zap,
} from "lucide-react";

/** Semantic icon keys used across the app instead of raw emoji. */
export const APP_ICONS = {
  activity: Activity,
  award: Award,
  book: BookOpen,
  brain: Brain,
  building: Building2,
  calendar: Calendar,
  check: CircleCheck,
  help: CircleHelp,
  clipboard: ClipboardList,
  movie: Clapperboard,
  cookie: Cookie,
  flame: Flame,
  science: FlaskConical,
  gamepad: Gamepad2,
  globe: Globe,
  handshake: Handshake,
  languages: Languages,
  landmark: Landmark,
  lightbulb: Lightbulb,
  link: Link2,
  mail: Mail,
  medal: Medal,
  message: MessageSquare,
  palette: Palette,
  pin: Pin,
  radio: Radio,
  rocket: Rocket,
  settings: Settings,
  shield: Shield,
  shieldCheck: ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  telescope: Telescope,
  trophy: Trophy,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof APP_ICONS;

/** Category slug → consistent Lucide icon. */
export const CATEGORY_ICONS: Record<string, AppIconName> = {
  geography: "globe",
  sports: "medal",
  entertainment: "movie",
  history: "landmark",
  "science-and-nature": "science",
  "art-and-literature": "palette",
  languages: "languages",
  trivia: "brain",
};

export function categoryIconName(slug: string): AppIconName {
  return CATEGORY_ICONS[slug] ?? "sparkles";
}
